openapi: 3.0.0
info:
  title: Delivery System API
  description: |
    API Spec for Delivery System
  version: 1.0.1
servers:
  - url: http://api.example.com/v1
    description: Production Server
paths:
